config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#	devise_for :users
	devise_for :users, controllers: { registrations: 'users/registrations'}
	#devise_for :users, :controllers => { :registrations => :registrations }
    root                                 'static_pages#index'
    get 'new_cat',		         	             to: 'categories#new'

    get 'contact_us',                        to: 'contacts#new'

    resources :contacts, only: [:new, :create, :index]
    resources :categories
    resources :jobs do 
      collection do
        get 'show_result'
      end
    end
    
    resources :users, only:[:show] do
      collection do 
        get 'show_applicant'
        get 'new_release'
        get 'show_employer'
        get 'show_employer_jobs'
      end
    end

    get '/users/show_applicant/:id'               => 'users#show_applicant', as: :show_applicant
    get '/users/show_employer/:id'                => 'users#show_employer', as: :show_employer
    get '/users/show_employer_jobs/:id'           => 'users#show_employer_jobs', as: :show_employer_jobs
   # get '/users/show_applicant/'        => 'users#show_applicant', as: :show_applicant
    #get '/users/new_release'               => 'users#new_release', as: :new_release

   	resources :applicants, only:[:index, :create, :show, :destroy] do
   			collection do
   			get 'submitted'
   	end
   	end
  
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :jobs, dependent: :destroy
 
  validates :name, presence: :true
  validates :company, presence: :true
  validates :address, presence: :true
  validates :overview, presence: :true
  validates :overview, presence: :true
  validates :working_hours, presence: :true
  validates :benefits, presence: :true
  mount_uploader :picture, PictureUploader
  validate :picture_size

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable, :lockable


  private
    def picture_size
      if picture.size > 5.megabytes
        errors.add(:picture, "Should less than 5 megabytes!")
      end
    end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
  protected

    
    def after_update_path_for(resource)
      current_user
    end

    #Remider: you have to include the after_in_active_sign_up_path_for if the registration is confirmable
    def after_sign_up_path_for(resource)
      new_user_session_path
    end

    def after_inactive_sign_up_path_for(resource)
      new_user_session_path
    end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	#before_action :signed_user, only:[:show, :show_applicant]
	before_action :correct_user, only:[:show, :show_applicant]
	def show
		@jobs = current_user.jobs.paginate(page: params[:jobs_page], per_page: 10)
		@app_jobs = current_user.jobs.joins(:user, :applicants).group('jobs.id').paginate(page: params[:app_jobs], per_page: 10)

	end

	def show_applicant
		@applicant = Applicant.find(params[:id])
		respond_to do |format|
		 format.js {render 'show_applicant'} 
		end
	end

	def show_employer
		@employer = User.find(params[:id])
	end	

	
	
	private 
		def signed_user
			unless user_signed_in?
				redirect_to jobs_url, alert: "You don't have a previlige"
			end
		end

		def correct_user
			unless current_user.eql? User.find(params[:id])
				redirect_to jobs_url, alert: "You don't have a previlige"
			end
		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_candidates_jobs.html.erb
<div class="row">
	<div class="col-sm-12 entry-div">
			<div class="thumbnail entry-padding">
				<% if @app_jobs.present? %>
					<h3 class="text-center">Candidates/Applicants</h3>
					<div class="table-responsive">
						<table class="table">
							<% @app_jobs.each do |apps| %>
								<thead>
									<th class="danger text-center" colspan="5"><%= apps.position %></th>
								</thead>
								<thead>
									<th>Name</th>
									<th>Date Applied</th>
									<th>Email</th>
									<th>Contact</th>
									<th ></th>
								</thead>
								<% apps.applicants.each do|app| %>
									<tr class="active">
										<td><%= app.name %></td>
										<td class="hidden-xs hidden-sm"><%= app.created_at.strftime('%B %d, %Y') %></td>
										<td><%= app.email %>
										<td><%= app.contact %>
										<td>
											<span class="pull-right">
										<!--		 #link_to 'View', show_applicant_path(app), remote: true  -->
											<%= link_to 'Download CV', app.resume_url %>
											<%= link_to 'Delete', app, method: :delete, data: {confirm: "Are you sure?"} %>	

											</span>
										</td>
									</tr>
								<% end %><!--- eand of apps.applicat.each-->
						<% end %><!-- end of @app-jobs -->
						</table>
					</div>
					<%= will_paginate @app_jobs, class: 'text-center', param_name: 'app_jobs' %>
				<% else %>
					<div class="alert alert-warning text-center"><h3>No Applicants</h3></div>
				<% end %>
			</div>
	</div>
</div>
 <div id="commentUserModal"> <%= render 'show_applicant' %></div>

app/views/users/_new_release.html.erb
<div id="ajax-modal" class="modal hide fade" tabindex="-1">
  <div class='modal-header'>
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3 class="modal-title">Campustask</h3>
  </div>
  <div class='modal-body'>
    <div class="modal-body-content"></div>
    <div class="ajax-loader"></div>
  </div>
  <div class='modal-footer'>
    <button type="button" data-dismiss="modal" class="btn">Close</button>
  </div>
</div>

app/views/users/_posted_jobs.html.erb
<div class="row">
		<div class="col-sm-12 entry-div">
			<div class="thumbnail entry-padding">
				<% if @jobs.present? %>
					<h3 class="text-center">Your Posted Jobs</h3>
					<table class="table">
						<thead>
							<th>Job</th>
							<th colspan="2" class="hidden-sm hidden-xs">Date Posted / Updated</th>
							
						</thead>
						<% @jobs.each do |job| %>
								<tr class="active">
									<td><%= job.position %></td>
									<td class="hidden-xs hiddnen-sm"><%= job.updated_at.strftime('%B %d, %Y') %></td>
									<td style="text-align: right;">
									<%= link_to 'View', job %>
									<%= link_to 'Edit', edit_job_path(job) %>
									<%= link_to 'Delete', job, method: :delete, data: {confirm: "Are you Sure?"} %>
									
									</td>
								</tr>
						<% end %>

						</table>
						<%= will_paginate @jobs, class: 'text-center', param_name: 'jobs_page' %>
						
				<% else %>
					<div class="alert alert-warning text-center"><h3>No Posted Jobs</h3></div>
				<% end %>
			

			</div>
		</div>
	</div>

app/views/users/_show_applicant.html.erb
<div id="commenterModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
   <div class="modal-dialog modal-md"> 
    <div class="modal-content"> 
      <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h3 class="modal-title text-center">Candidate Information</h3>
      </div>
      <div class="modal-body" id="commentUserModal"> 
        <div class="row">
          <div class="col-sm-6">
            <% if @applicant.present? %>
              <h3><%= @applicant.name %></h3>
              <p>Email: <%= @applicant.email %></p>
              <p>Address: <%= @applicant.address %></p>
              <p>Contact: <%= @applicant.contact %></p>
              <p><%= link_to 'Download CV', @applicant.resume.url %></p>
            <% end %>
          </div>
          <div class="col-sm-6 hidden-xs hidden-sm">
            <p>
              <%= if current_user.picture?
                    image_tag current_user.picture.url, class: 'pull-right'
                  else
                    image_tag 'http://res.cloudinary.com/gibetirol/image/upload/c_scale,h_150,w_150/v1464517296/company-logo-designs_zf13mh.jpg', class: 'pull-right'
                  end
                %>  
            </p>
          </div>
        </div><!-- end of row -->
      </div> <!-- End of modal body -->
      <div class="modal-footer"> 
        <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">OK</button> 
      </div> 
    </div> <!-- modal-content --> 
  </div> <!-- modal-dialog --> 
</div> <!-- modal --> 

app/views/users/show.html.erb
<% provide(:title, "#{current_user.company}") %>
<div class="col-sm-12 entry-div">
	<div class="thumbnail">
		<div class="thumbnail entry-padding no-border">
			
			<div class="row">
				<div class="col-sm-2">
					<div class="thumbnail no-border">
						<%= if current_user.picture?
								image_tag current_user.picture.url
							else
								image_tag 'http://res.cloudinary.com/gibetirol/image/upload/c_scale,h_150,w_150/v1464517296/company-logo-designs_zf13mh.jpg'
							end
						%>
					</div>
				</div>
				<div class="col-sm-4 <%= "text-center" if browser.device.mobile?%> ">
					<div class="thumbnail no-border">
						<h3 class="company"><%= current_user.company %></h3>
						 <strong>Registrant Name: <%= current_user.name %></strong><br />
						 Date of Registration: <%= current_user.created_at.strftime('%B %d, %Y') %><br >
						 <%= link_to 'Post a Job', new_job_path, class: 'btn btn-primary', style: 'margin-top: 10px;' %>
					</div>
				</div>	
			</div>
		</div>
		
	<!-- Insert posted Jobs -->
	<%= render 'posted_jobs' %>
	
	<!-- Insert candidate list -->	
	<%= render 'candidates_jobs' %>
	</div><!-- main thumbnaill -->
</div><!-- main div -->

app/views/users/show_applicant.js.erb
$("#commentUserModal").html("<%= j render 'users/show_applicant' %>"); 
$("#commenterModal").modal('show'); 

app/views/users/show_employer.html.erb
<% provide(:title, "#{@employer.company}") %>
<%= render 'shared/sidebar_category' %>
<div class="col-sm-9 entry-div">
	<div class="thumbnail entry-padding">
		<%=  if @employer.picture?
				image_tag @employer.picture.url
			else
				image_tag 'http://res.cloudinary.com/gibetirol/image/upload/c_scale,h_150,w_150/v1464517296/company-logo-designs_zf13mh.jpg'
			end
		 %>
		<h3 class="text-center"><%= @employer.company %></h3>
		<hr class="line" />
		<div class="thumbnail no-border">
			<h3>Address</h3>
			<p>
				<%= @employer.address.html_safe %>
			</p>
			<h3>Company's Overview</h3>
			<p>
				<%= @employer.overview.html_safe %>
			</p>
			<h3>Benefits</h3>
			<p>
				<%= @employer.benefits %>
			</p>
			<h3>Working Days and Hours</h3>
			<p>
				<%= @employer.working_hours %>
			</p>
			<hr class="line" />
			<h3>Jobs Available: <%= @employer.jobs.count %></h3>
			<ul>
						<% @employer.jobs.each do |job| %>
							<li><%= link_to job.position, job %></li>
						<% end %>
			</ul>
		</div><!-- end of thumbnail -->
	</div><!-- end of entry-padding -->
</div><!-- end of column 9 -->