config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#	devise_for :users
	devise_for :users, controllers: { registrations: 'users/registrations'}
	#devise_for :users, :controllers => { :registrations => :registrations }
    root                                 'static_pages#index'
    get 'new_cat',		         	             to: 'categories#new'

    get 'contact_us',                        to: 'contacts#new'

    resources :contacts, only: [:new, :create, :index]
    resources :categories
    resources :jobs do 
      collection do
        get 'show_result'
      end
    end
    
    resources :users, only:[:show] do
      collection do 
        get 'show_applicant'
        get 'new_release'
        get 'show_employer'
        get 'show_employer_jobs'
      end
    end

    get '/users/show_applicant/:id'               => 'users#show_applicant', as: :show_applicant
    get '/users/show_employer/:id'                => 'users#show_employer', as: :show_employer
    get '/users/show_employer_jobs/:id'           => 'users#show_employer_jobs', as: :show_employer_jobs
   # get '/users/show_applicant/'        => 'users#show_applicant', as: :show_applicant
    #get '/users/new_release'               => 'users#new_release', as: :new_release

   	resources :applicants, only:[:index, :create, :show, :destroy] do
   			collection do
   			get 'submitted'
   	end
   	end
  
  
end

app/views/resume/application_sent.html.erb
<div style="background-color: #f1f1f1; padding: 30px; text-align: center;" >
	<h1 class="text-center">Pinoy Job Portal</h1>
	<strong>Hi <%= @applicant.name %></strong>
	<p>
		Your application has been submitted!
	</p>
	<p>
		Thank you for submitting your application to Pinoy Job Portal. We wish you good luck!
	</p>
	<p style="padding-bottom: 20px;">
		Always;
	</p>
	<p>
		Your Pinoy Job Portal
	</p>
	<p>
		<%= link_to 'View More Jobs', jobs_url %>
	</p>
</div>

app/views/resume/application_sent.text.erb
Pinoy Job Portal

Hi <%= @applicant.name %>
	
Your application has been submitted!

Thank you for submitting your application to Pinoy Job Portal. We wish you good luck!

Always;

Your Pinoy Job Portal