config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
#	devise_for :users
	devise_for :users, controllers: { registrations: 'users/registrations'}
	#devise_for :users, :controllers => { :registrations => :registrations }
    root                                 'static_pages#index'
    get 'new_cat',		         	             to: 'categories#new'

    get 'contact_us',                        to: 'contacts#new'

    resources :contacts, only: [:new, :create, :index]
    resources :categories
    resources :jobs do 
      collection do
        get 'show_result'
      end
    end
    
    resources :users, only:[:show] do
      collection do 
        get 'show_applicant'
        get 'new_release'
        get 'show_employer'
        get 'show_employer_jobs'
      end
    end

    get '/users/show_applicant/:id'               => 'users#show_applicant', as: :show_applicant
    get '/users/show_employer/:id'                => 'users#show_employer', as: :show_employer
    get '/users/show_employer_jobs/:id'           => 'users#show_employer_jobs', as: :show_employer_jobs
   # get '/users/show_applicant/'        => 'users#show_applicant', as: :show_applicant
    #get '/users/new_release'               => 'users#new_release', as: :new_release

   	resources :applicants, only:[:index, :create, :show, :destroy] do
   			collection do
   			get 'submitted'
   	end
   	end
  
  
end

app/views/layouts/_footer.html.erb
<div class="footer-container">
   
      <div class="row">
   		<div class="col-sm-6">
   			<h3 class="text-center">Latest Jobs</h3>
   			<ul class="footer-latest-job">
   				<% @latest_jobs.each do |latest_job| %>
   					<li><%= link_to latest_job.position, latest_job %></li>
   				<% end %>
   			</ul>
   		</div>
   		<div class="col-sm-6">
   			<h3 class="text-center">Our Clients</h3>
   			<ul class="footer-latest-job">
   				<% @clients.each do |client| %>
   					<li><%= link_to client.company, show_employer_path(client) %></li>
   				<% end %>
   			</ul>
   		</div>
   		
      </div><!-- end for Row -->
   
</div> <!-- End of  footer container -->

app/views/layouts/_footer2.html.erb
<div class="footer-bottom">
	<div class="row">
		<div class="col-sm-6 footer-left">
			<%= link_to 'About Us', '#' %> |
			<%= link_to 'Terms of Use', '#' %> |&nbsp;
			<%= link_to 'Privacy Policy', '#' %> |&nbsp;
			<%= link_to 'Send Feedback', contact_us_path %>

		</div>
		<div class="col-sm-6 footer-right">
			Copyright &copy; 2018 Pinoy Job Portal
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">Job Pinoy Portal</a>
    </div><!-- end of navbar-header -->

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right" >
        <li><%= link_to 'Home', root_url %></li>
        <li><%= link_to 'Contact Us', contact_us_path %></a></li>
        <li><%= link_to 'View Jobs', jobs_path %></li>
        <% if user_signed_in? %>
          <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.name %><span class="caret"></span></a>
                <ul class="dropdown-menu">
                    <li><%= link_to 'Dashboard', current_user %></li>
                    <li><%= link_to 'Edit My Profile', edit_user_registration_path %></li>
                    <li><%= link_to 'Signout', destroy_user_session_path, method: :delete %></li>
                </ul>
           </li><!-- end drop down -->
        <% else %>
            <li><%= link_to 'Employers', new_user_session_path %> </li>
        <% end %>
      </ul>

    </div><!-- nav-collapse -->

  </div>
</nav>

app/views/layouts/_header2.html.erb
<div class="container-fluid white">
	<%
		if browser.device.mobile?
			logo = search = 'text-center' 
		else
			logo = 'pull-left'
			search = 'pull-right'
		end if
	%>
	<div class="container" style="padding-top: 10px; padding-bottom: 10px;">
		<div class="row">
			<div class="col-sm-5 <%= logo %>">
				<%= image_tag 'http://res.cloudinary.com/gibetirol/image/upload/v1463751114/logo_l1qd3i.png' %>
			</div>
			<!--
			<div class="col-sm-7">
				<form class="form-inline <%= search %>">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search Jobs/Keywords">
					</div>
					<button type="submit" class="btn btn-warning">
						<span class="glyphicon glyphicon-search"></span>&nbsp;Search
					</button>
				</form>		
			</div>	
			-->
			<div class="col-sm-7">
				<%= form_tag(show_result_jobs_path, method: :get, id: :search_form, class: "form-inline #{search}" ) do %>
						<div class="form-group">
							<%= text_field_tag :search, params[:search], placeholder: 'Jobs/Keywords', class: 'form-control' %>
						</div>
					
						<%= button_tag type: 'submit', class: 'btn btn-warning' do %>
							<span class="glyphicon glyphicon-search"></span>&nbsp;Search
						<% end %>

				<% end %>
			</div>

		</div>
	</div>

</div>

app/views/layouts/_slider.html.erb
<div class="container-fluid">
	<div class="row">
		<div class="col-sm-12" style="position: fixed; padding: 0; top: 0;">
			<div id="job-slider" class="carousel slide" data-ride="carousel">
				<!-- Indicators -->
				<ol class="carousel-indicators">
					<li data-target="#job-slider" data-slide-to="0" class="active"></li>
					<li data-target="#job-slider" data-slide-to="1"></li>
					<li data-target="#job-slider" data-slide-to="2"></li>
				</ol>
				<!-- Wrapper for slides -->
				<div class="carousel-inner" role="listbox">
					<div class="carousel-caption">
							<div class="full-width text-center">
								<h1>Find the best jobs around the Philippines</h1>
								<p>
									<%= link_to 'Latest Jobs', jobs_path, class: 'btn btn-success' %>
									<%= link_to 'Employer? Register With Us', new_user_registration_path, class: 'btn btn-warning' %>
								</p>
							</div>
						</div>


					<div class="item active">
						<%= image_tag 'http://res.cloudinary.com/gibetirol/image/upload/v1466610232/slide1_bhkajq.jpg', class: 'img-res' %>
											</div><!-- end of item i -->
					<div class="item">
						<%= image_tag 'http://res.cloudinary.com/gibetirol/image/upload/v1466416693/slide-5_kxnamr.jpg',class: 'img-res' %>
					</div><!-- end of item 2 -->

					<div class="item">	
						<%= image_tag 'http://res.cloudinary.com/gibetirol/image/upload/v1466610232/slide2_pb1bru.jpg', class: 'img-res' %>
					</div><!-- end of item 3 -->

				</div><!-- carouse inner -->

				<!-- Controls for Next and Previous -->
				<!-- controls or next and prev buttons -->
 						<a class="left carousel-control" href="#job-slider" role="button" data-slide="prev">
 							<span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
 							<span class="sr-only">Previous</span>
 						</a>
 						<a class="right carousel-control" href="#job-slider" role="button" data-slide="next">
 							<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
 							<span class="sr-only">Next</span>
 						</a>
			</div>
		</div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= favicon_link_tag 'http://res.cloudinary.com/gibetirol/image/upload/v1466582511/logo_axgudc.png' %>
  <%= csrf_meta_tags %>
</head>
<body>
    
    <%= render 'layouts/header' %>
    <%= render 'layouts/slider' if current_page?(controller: '/static_pages', action: 'index') %>
    <%= render 'layouts/header2' unless current_page?(controller: '/static_pages', action: 'index') %>
    
    <div class="container">
      <div class="row">
        <div class="col-sm-12">

          <% flash.each do |key,value| %>
            <div class="alert alert-<%= key %>">
              <%= value %>
            </div>
          <% end %>
        </div>
        <%= yield %>
      </div>
    </div>
    <%= render 'layouts/footer' unless current_page?(controller: '/static_pages', action: 'index') %>   
    <%= render 'layouts/footer2' unless current_page?(controller: '/static_pages', action: 'index') %>
    <%= debug(params) if Rails.env.development? %>

    
</body>
</html>